apiVersion: apps/v1
kind: Deployment
metadata:
  name: grayworld-deployment
  labels:
    app: grayworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grayworld
  template:
    metadata:
      labels:
        app: grayworld
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web
        imagePullPolicy: IfNotPresent
        ports:
        - name: node-port
          containerPort: 80
