apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-affinity-toleration
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: k8s-demo
        imagePullPolicy: IfNotPresent
        image: amitvashist7/k8s-tiny-web
        ports:
        - name: node-port
          containerPort: 80
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "myapp"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - prod
